server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: items-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/items/**
          filters: []

        - id: orders-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
          filters: []

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**


        - id: auth-user
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters: []

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    org.springframework.web.server.adapter: DEBUG